name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6~=6.9 pyinstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: fusor-windows
          path: dist/main.exe
      - name: Upload release asset (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt runtime libs
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libxkbcommon-x11-0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6~=6.9 pyinstaller
      - name: Build binary with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile main.py
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: fusor-linux
          path: dist/main
      - name: Upload release asset (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main
